server:
 port: 8080
eureka:
 instance:
    hostname: localhost
    preferIpAddress: true
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: userservice
        uri: lb://userservice
        predicates:
        - Path=/userservice/**
      - id: pitchservice
        uri: lb://pitchservice
        predicates:
        - Path=/pitchservice/**
      - id: bookingservice
        uri: lb://bookingservice
        predicates:
        - Path=/bookingservice/**